// Auto-generated by `supabase gen types typescript`
// This file will be overwritten — do not edit manually.

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          email: string;
          xp: number;
          level: number;
          created_at: string;
        };
        Insert: {
          id: string;
          username: string;
          email: string;
          xp?: number;
          level?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          username?: string;
          email?: string;
          xp?: number;
          level?: number;
          created_at?: string;
        };
      };
      habits: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          category: string;
          frequency: string;
          is_archived: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          category: string;
          frequency?: string;
          is_archived?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          category?: string;
          frequency?: string;
          is_archived?: boolean;
          created_at?: string;
        };
      };
      completions: {
        Row: {
          id: string;
          habit_id: string;
          completed_at: string;
          xp_earned: number;
        };
        Insert: {
          id?: string;
          habit_id: string;
          completed_at?: string;
          xp_earned?: number;
        };
        Update: {
          id?: string;
          habit_id?: string;
          completed_at?: string;
          xp_earned?: number;
        };
      };
      streaks: {
        Row: {
          id: string;
          habit_id: string;
          current_count: number;
          longest_count: number;
          last_completed_at: string | null;
        };
        Insert: {
          id?: string;
          habit_id: string;
          current_count?: number;
          longest_count?: number;
          last_completed_at?: string | null;
        };
        Update: {
          id?: string;
          habit_id?: string;
          current_count?: number;
          longest_count?: number;
          last_completed_at?: string | null;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
