import json, sys
from base import BODY, HAIR, TUNIC
from hats import HATS, SHOWS_HAIR
from outfits import OUTFITS
from accessories import ACCESSORIES
HAT_C = {'hat_adventurer': ('#8B7355', '#b5402f'), 'hat_knight': ('#8a95a5', '#c0c0c0'), 'hat_pirate': ('#2a2a2a', '#e8c35a'),
     'hat_wizard': ('#4B0082', '#f0c43c'), 'hat_viking': ('#8a7a60', '#eee8dc'), 'hat_samurai': ('#8B0000', '#e0b84a'),
     'hat_crown': ('#d8324a', '#DAA520'), 'hat_halo': ('#fff6c2', '#FFD700'), 'hat_dragon': ('#5a0a0a', '#c0392b'),
     'hat_pumpkin': ('#e8742a', '#4a8a2a'), 'hat_winter': ('#c0392b', '#f2f2f2')}
OUT_C = {'outfit_peasant': ('#8B7355', '#6b5b45', '#c9a86a'), 'outfit_leather': ('#8B4513', '#654321', '#caa25a'),
     'outfit_forest': ('#2d6a2e', '#1a3a10', '#8bc34a'), 'outfit_mage': ('#4B0082', '#6A0DAD', '#f0c43c'),
     'outfit_ice': ('#7fd3f7', '#0288D1', '#e0f7ff'), 'outfit_crimson': ('#B71C1C', '#880E0E', '#d9d9d9'),
     'outfit_golden': ('#DAA520', '#B8860B', '#fff3b0'), 'outfit_royal': ('#6a1b9a', '#4A148C', '#f0c43c'),
     'outfit_shadow': ('#3a3a5c', '#262640', '#7b68ee')}
ACC_C = {'acc_shield_wood': ('#9a6b3a', '#6b6b6b'), 'acc_shield': ('#8a95a5', '#b22222'), 'acc_sword': ('#d0d6de', '#8B7355'),
     'acc_flame_sword': ('#ffb347', '#e0452a'), 'acc_scarf': ('#e94560', '#f0c43c'), 'acc_amulet': ('#7b68ee', '#e0b84a'),
     'acc_cape': ('#9b1b1b', '#DAA520'), 'acc_wings': ('#eeeeee', '#FFD700'), 'acc_aura': ('#7B68EE', '#c77dff'),
     'acc_autumn_scarf': ('#b5541c', '#e8b04a')}
out = []; w = out.append
w("// Generated by scripts/sprites/gen_ts.py from the 32x32 sprite sources (pixel art direction, ADR 011).")
w("// Each sprite is 32 rows of 32 characters; '.' is transparent. Characters are")
w("// resolved by the palette of their layer in pixel-avatar.tsx. Edit the .py sources, not this file.")
w(""); w("export const GRID = 32;"); w("")
def arr(name, rows):
    w(f"export const {name}: string[] = ["); [w(f"  '{r}',") for r in rows]; w("];"); w("")
arr('BODY', BODY); arr('HAIR', HAIR); arr('TUNIC', TUNIC)
def rec(name, d, comment):
    w(f"// {comment}"); w(f"export const {name}: Record<string, string[]> = {{")
    for k, rows in d.items():
        w(f"  {k}: ["); [w(f"    '{r}',") for r in rows]; w("  ],")
    w("};"); w("")
rec('HAT_SPRITES', HATS, "Hats replace the hair, except those in HATS_OVER_HAIR.")
w(f"export const HATS_OVER_HAIR = new Set({json.dumps(sorted(SHOWS_HAIR))});"); w("")
rec('OUTFIT_SPRITES', OUTFITS, "Outfits cover the torso (and the legs for robes and cloaks).")
w("// 'back' accessories are drawn behind the hero, 'front' ones over the outfit.")
w("export const ACCESSORY_SPRITES: Record<string, { layer: 'back' | 'front'; rows: string[] }> = {")
for k, (layer, rows) in ACCESSORIES.items():
    w(f"  {k}: {{"); w(f"    layer: '{layer}',"); w("    rows: ["); [w(f"      '{r}',") for r in rows]; w("    ],"); w("  },")
w("};"); w("")
w("// Item colors: [main, accent]. Shades and highlights are derived.")
w("export const HAT_COLORS: Record<string, [string, string]> = {"); [w(f"  {k}: ['{a}', '{x}'],") for k, (a, x) in HAT_C.items()]; w("};"); w("")
w("// [primary, secondary, trim]")
w("export const OUTFIT_COLORS: Record<string, [string, string, string]> = {"); [w(f"  {k}: ['{p}', '{q}', '{x}'],") for k, (p, q, x) in OUT_C.items()]; w("};"); w("")
w("export const ACCESSORY_COLORS: Record<string, [string, string]> = {"); [w(f"  {k}: ['{a}', '{x}'],") for k, (a, x) in ACC_C.items()]; w("};")
open(sys.argv[1], 'w', encoding='utf-8', newline='\n').write("\n".join(out) + "\n")
print('written', sys.argv[1])
